#!/bin/bash

if [ $(checkLs.sh | wc -l) -eq 110 -o $(checkLs.sh | wc -l) -eq 124 ]; then
echo try sending command checkLs.sh to check the contents of the channels directories...
else

# find directories with data to sort
find . -name "rplhighpass.mat" | adirfiles | sort > highpassdirs.txt
# find completed learn jobs
find . -name "learn_job*.o*" | sort > learnfiles.txt
# find directories with completed learn jobs
cat learnfiles.txt | adirfiles | sort | uniq > learndirs.txt
# find directories with completed learn jobs that found sua
grep -l sigma $(cat learnfiles.txt) | adirfiles | sort > suadirs.txt
# find directories with completed decode jobs
find . -name "hmmsort.mat" | adirfiles | sort > hmmsortdirs.txt
# find directories with completed learn jobs that did not find any sua
grep -l spikeforms $(cat learnfiles.txt) | adirfiles | sort | uniq > nosuadirs.txt
# find directories where hmmlearn failed
grep -L sigma $(cat learnfiles.txt) | xargs grep -L spikeforms | adirfiles | uniq > hmmfail.txt
# find directories where hmmlearn has not finished
comm -23 highpassdirs.txt learndirs.txt > nolearndirs.txt
# find directories where hmmsort.mat have not been created
comm -23 suadirs.txt hmmsortdirs.txt > nohmmsortdirs.txt
# find directories where hmmdecode has finished so we can cross-check
# with nodecodedirs.txt to see if hmmdecode needs to be re-run
find . -name "decode_job*.o*" | adirfiles | sort | uniq > decodedirs.txt
comm -12 nohmmsortdirs.txt decodedirs.txt > decodefail.txt
comm -23 nohmmsortdirs.txt decodedirs.txt > nodecodedirs.txt
# find directories with completed transfer jobs
find . -name "transferred.txt" | adirfiles | sort > transferreddirs.txt

wc -l highpassdirs.txt learndirs.txt suadirs.txt hmmsortdirs.txt nosuadirs.txt

echo "Still sorting..."
for i in `cat nolearndirs.txt`; do
    echo $i
    sed -n '3p' $i/decode_job????.pbs
done

echo "Not decoded..."
for i in `cat nodecodedirs.txt`; do
    echo $i
    sed -n '3p' $i/decode*pbs
done

echo "hmmlearn failed..."
cat hmmfail.txt
for i in $(cat hmmfail.txt); do 
	echo $i; 
	tail -n 20 $i/learn*.o*; 
done

echo "hmmdecode failed..."
cat decodefail.txt
for i in $(cat decodefail.txt); do 
    echo $i; 
    tail -n 20 $i/decode*.o*; 
done

find . -name 'channel*' > allchannels.txt

echo "Not transferred..."
cat allchannels.txt transferreddirs.txt nodecodedirs.txt hmmfail.txt nolearndirs.txt | sort | uniq -u > notransferreddirs.txt

echo "Failed transferred..."
find . -name 'transfer_job0000.pbs.e*' | adirfiles > allTE.txt
cat notransferreddirs.txt allTE.txt | sort | uniq -d > failedTransferred.txt
cat failedTransferred.txt

rm allTE.txt

#rm highpassdirs.txt learndirs.txt learnfiles.txt suadirs.txt hmmsortdirs.txt nosuadirs.txt

wc -l hmmfail.txt nolearndirs.txt nodecodedirs.txt transferreddirs.txt notransferreddirs.txt failedTransferred.txt
fi
